"""
Recommendation Engine for ECL Segments

Generates business recommendations and verdicts based on:
- ECL metrics (PD, LGD, EAD, ECL)
- Risk thresholds
- Retrieved segment data from RAG queries
"""

import logging
from typing import List, Dict
from core.config import PD_THRESHOLD_HIGH, PD_THRESHOLD_MEDIUM

# Initialize logger
logger = logging.getLogger(__name__)


def generate_recommendation(pd: float, ecl: float) -> str:
    """
    Generate business recommendation based on PD and ECL values.
    
    Args:
        pd: Probability of Default (0-1)
        ecl: Expected Credit Loss (dollar amount)
    
    Returns:
        Recommendation string
    """
    if pd >= PD_THRESHOLD_HIGH:
        return "REDUCE DISBURSEMENT - High default risk detected"
    elif pd >= PD_THRESHOLD_MEDIUM:
        return "INCREASE INTEREST RATE - Medium risk, adjust pricing"
    else:
        return "NO CHANGE - Low risk segment"


def get_risk_level(pd: float) -> str:
    """
    Determine risk level based on PD.
    
    Args:
        pd: Probability of Default (0-1)
    
    Returns:
        Risk level: "HIGH", "MEDIUM", or "LOW"
    """
    if pd >= PD_THRESHOLD_HIGH:
        return "HIGH"
    elif pd >= PD_THRESHOLD_MEDIUM:
        return "MEDIUM"
    else:
        return "LOW"


def generate_segment_verdict(segment_data: Dict) -> Dict:
    """
    Generate detailed verdict for a single segment.
    
    Args:
        segment_data: Dictionary with segment information
            {segment_type, segment, total_loans, pd, lgd, ead, ecl}
    
    Returns:
        Dictionary with verdict and recommendations
    """
    pd = segment_data.get("pd", 0)
    ecl = segment_data.get("ecl", 0)
    
    risk_level = get_risk_level(pd)
    recommendation = generate_recommendation(pd, ecl)
    
    # Additional insights
    insights = []
    
    # Special handling for age groups
    segment_name = segment_data.get("segment", "").lower()
    if "senior" in segment_name or "senior_citizen" in segment_name:
        if pd >= PD_THRESHOLD_MEDIUM:
            insights.append("Senior citizens showing elevated risk - consider additional income verification")
        else:
            insights.append("Senior citizens segment performing well - maintain current policies")
    
    if pd >= PD_THRESHOLD_HIGH:
        insights.append(f"Default rate of {pd*100:.1f}% is significantly high")
        insights.append("Consider stricter underwriting criteria")
    
    if ecl > 5000:
        insights.append(f"High expected loss: ${ecl:,.2f} per loan")
        insights.append("Review pricing strategy and collateral requirements")
    
    if segment_data.get("total_loans", 0) < 100:
        insights.append("Limited sample size - results may not be statistically significant")
    
    return {
        "segment_type": segment_data.get("segment_type"),
        "segment": segment_data.get("segment"),
        "risk_level": risk_level,
        "recommendation": recommendation,
        "insights": insights,
        "metrics": {
            "pd": pd,
            "ecl": ecl,
            "total_loans": segment_data.get("total_loans", 0)
        }
    }


def generate_query_verdict(
    query: str,
    segments: List[Dict],
    rag_answer: str
) -> Dict:
    """
    Generate comprehensive verdict for a RAG query.
    
    Args:
        query: Original user query
        segments: List of retrieved segment dictionaries
        rag_answer: Answer generated by RAG engine
    
    Returns:
        Dictionary with verdict, recommendations, and analysis
    """
    if not segments:
        # Log detailed error for diagnosis
        query_excerpt = query[:50] + "..." if len(query) > 50 else query
        logger.error(
            f"[VERDICT] Starved - Query: '{query_excerpt}', "
            f"RAG answer length: {len(rag_answer)}, "
            f"Segments: 0 (filtered out or not found)"
        )
        
        return {
            "query": query,
            "verdict": "Insufficient data access",
            "rag_answer": rag_answer,
            "recommendations": [],
            "summary": "No accessible segments after filtering. This may be due to insufficient permissions or no matching data. Contact your administrator to request access to segment data.",
            "debug": {
                "segments_found": 0,
                "possible_causes": [
                    "User lacks read permissions for relevant segment types",
                    "No data matches the query criteria",
                    "RBAC filtering removed all results"
                ],
                "admin_action": "Grant 'read' permissions on segment types like 'loan_intent', 'person_gender', 'age_group', etc."
            }
        }
    
    # Generate verdict for each segment
    segment_verdicts = [generate_segment_verdict(seg) for seg in segments]
    
    # Overall risk assessment
    avg_pd = sum(s["metrics"]["pd"] for s in segment_verdicts) / len(segment_verdicts)
    total_ecl = sum(s["metrics"]["ecl"] for s in segment_verdicts)
    
    overall_risk = get_risk_level(avg_pd)
    
    # Compile recommendations
    recommendations = []
    for verdict in segment_verdicts:
        rec = {
            "segment": verdict["segment"],
            "segment_type": verdict["segment_type"],
            "risk": verdict["risk_level"],
            "action": verdict["recommendation"]
        }
        recommendations.append(rec)
    
    # Generate summary
    high_risk_count = sum(1 for v in segment_verdicts if v["risk_level"] == "HIGH")
    medium_risk_count = sum(1 for v in segment_verdicts if v["risk_level"] == "MEDIUM")
    
    summary_parts = []
    if high_risk_count > 0:
        summary_parts.append(f"{high_risk_count} high-risk segment(s) identified")
    if medium_risk_count > 0:
        summary_parts.append(f"{medium_risk_count} medium-risk segment(s) identified")
    
    summary_parts.append(f"Average PD: {avg_pd*100:.1f}%")
    summary_parts.append(f"Total ECL across segments: ${total_ecl:,.2f}")
    
    summary = ". ".join(summary_parts) + "."
    
    return {
        "query": query,
        "verdict": overall_risk,
        "rag_answer": rag_answer,
        "recommendations": recommendations,
        "summary": summary,
        "segment_analysis": segment_verdicts,
        "metrics": {
            "average_pd": round(avg_pd, 4),
            "total_ecl": round(total_ecl, 2),
            "segments_analyzed": len(segments),
            "high_risk_count": high_risk_count,
            "medium_risk_count": medium_risk_count
        }
    }

